"""Materialize demo artifacts for replay mode (no LLM calls)."""

from __future__ import annotations

import json
from typing import Any

from temporalio import activity

from services.agents.graphs.implementation_graph import DEFAULT_APP, DEFAULT_TEST
from services.agents.tools.files import list_artifacts, write_file
from services.common.logging import get_logger

logger = get_logger(__name__)

_REQUIREMENTS = {
    "summary": "URL shortener with shorten, redirect, and click analytics.",
    "functional": [
        "Create short URL from long URL",
        "Redirect short URL to original",
        "Track click analytics",
    ],
    "non_functional": ["99.9% availability target", "P99 redirect < 100ms"],
    "acceptance_criteria": [
        "POST /shorten returns code",
        "GET /{code} redirects",
        "GET /stats/{code} returns counts",
    ],
    "assumptions": ["In-memory store acceptable for prototype"],
    "gaps": [],
    "mode": "replay",
}

_DESIGN = {
    "components": [
        {"name": "api", "role": "FastAPI HTTP layer"},
        {"name": "store", "role": "URL mapping persistence"},
        {"name": "analytics", "role": "click counters"},
    ],
    "data_model": {
        "urls": {
            "code": "str pk",
            "target": "str",
            "created_at": "datetime",
            "clicks": "int",
        }
    },
    "api_contract": [
        {"method": "POST", "path": "/shorten", "body": {"url": "string"}},
        {"method": "GET", "path": "/{code}", "response": "302 redirect"},
        {"method": "GET", "path": "/stats/{code}", "response": {"clicks": "int"}},
    ],
    "risks": ["Collision on short codes", "Open redirect abuse"],
    "mode": "replay",
}

_README = """# URL Shortener

Generated by the Agentic SDLC pipeline (replay mode).

## APIs
- `POST /shorten` — create short URL
- `GET /{code}` — redirect
- `GET /stats/{code}` — click analytics
- `GET /health` — health check
"""

_TEST_REPORT = {
    "passed": True,
    "coverage": 0.85,
    "findings": [],
    "mode": "replay",
}


def materialize_replay_artifacts_sync(run_id: str, scenario: str = "greenfield") -> dict[str, Any]:
    """Write the expected greenfield/brownfield/ambiguous artifact set for demos."""
    paths: dict[str, str] = {}
    paths["requirements"] = write_file(
        run_id, "requirements.json", json.dumps(_REQUIREMENTS, indent=2)
    )
    paths["design"] = write_file(run_id, "design.json", json.dumps(_DESIGN, indent=2))
    paths["app"] = write_file(run_id, "url_shortener/app.py", DEFAULT_APP)
    paths["tests"] = write_file(run_id, "url_shortener/test_app.py", DEFAULT_TEST)
    paths["readme"] = write_file(run_id, "url_shortener/README.md", _README)
    paths["requirements_txt"] = write_file(
        run_id,
        "url_shortener/requirements.txt",
        "fastapi\nuvicorn\nhttpx\npydantic\n",
    )
    paths["test_report"] = write_file(
        run_id, "test_report.json", json.dumps(_TEST_REPORT, indent=2)
    )
    paths["api_docs"] = write_file(
        run_id, "API.md", json.dumps(_DESIGN["api_contract"], indent=2)
    )
    if scenario == "brownfield":
        paths["change_notes"] = write_file(
            run_id,
            "CHANGE_NOTES.md",
            "# Brownfield changes (replay)\n\nRate limiting + Redis cache stubs.\n",
        )
    files = list_artifacts(run_id)
    logger.info(
        "replay_artifacts_materialized",
        run_id=run_id,
        scenario=scenario,
        file_count=len(files),
    )
    return {"artifacts": paths, "files": files, "scenario": scenario}


@activity.defn(name="materialize_replay_artifacts")
async def materialize_replay_artifacts(run_id: str, scenario: str = "greenfield") -> dict[str, Any]:
    return materialize_replay_artifacts_sync(run_id, scenario)
