"""Documenter graph."""

from __future__ import annotations

import json
from typing import Any

from services.agents import prompt_loader
from services.agents.nodes.llm import invoke_json
from services.agents.state import AgentState
from services.agents.tools.files import write_file
from services.common.logging import get_logger

logger = get_logger(__name__)


async def run(state: dict[str, Any]) -> dict[str, Any]:
    s = AgentState.model_validate(state)
    system = prompt_loader.get("documenter")
    user = (
        f"Requirements:\n{json.dumps(s.requirements or {}, indent=2)}\n"
        f"Design:\n{json.dumps(s.design or {}, indent=2)}\n"
        f"Test report:\n{json.dumps(s.test_report or {}, indent=2)}"
    )
    try:
        data = await invoke_json(
            system,
            user + '\nReturn JSON {"readme": "...", "api_docs": "..."}',
        )
        readme = data.get("readme") or "# URL Shortener\n"
        api_docs = data.get("api_docs") or ""
    except Exception as exc:  # noqa: BLE001
        logger.warning("documenter_fallback", error=str(exc))
        readme = (
            "# URL Shortener\n\n"
            "Generated by the Agentic SDLC pipeline.\n\n"
            "## APIs\n"
            "- `POST /shorten` — create short URL\n"
            "- `GET /{code}` — redirect\n"
            "- `GET /stats/{code}` — click analytics\n"
        )
        api_docs = json.dumps((s.design or {}).get("api_contract") or [], indent=2)

    r_path = write_file(s.run_id, "url_shortener/README.md", readme)
    a_path = write_file(s.run_id, "API.md", api_docs)
    return {
        "documentation": readme,
        "content": readme,
        "artifact": readme,
        "artifacts": {**(s.artifacts or {}), "readme": r_path, "api_docs": a_path},
        "structured": {"readme": r_path, "api_docs": a_path},
    }
