"""Implementer graph — writes URL shortener code artifacts."""

from __future__ import annotations

import json
from typing import Any

from services.agents import prompt_loader
from services.agents.nodes.llm import invoke_json
from services.agents.state import AgentState
from services.agents.tools.files import policy_gated_write, write_file
from services.common.logging import get_logger

logger = get_logger(__name__)

DEFAULT_APP = '''\
"""URL shortener service — generated by agentic SDLC implementer."""

from __future__ import annotations

import secrets
from datetime import UTC, datetime
from typing import Any

from fastapi import FastAPI, HTTPException
from fastapi.responses import RedirectResponse
from pydantic import BaseModel, HttpUrl

app = FastAPI(title="URL Shortener", version="0.1.0")

_STORE: dict[str, dict[str, Any]] = {}


class ShortenRequest(BaseModel):
    url: HttpUrl


class ShortenResponse(BaseModel):
    code: str
    short_url: str


class StatsResponse(BaseModel):
    code: str
    target: str
    clicks: int
    created_at: str


def _new_code(n: int = 7) -> str:
    return secrets.token_urlsafe(n)[:n]


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


@app.post("/shorten", response_model=ShortenResponse)
def shorten(body: ShortenRequest) -> ShortenResponse:
    code = _new_code()
    while code in _STORE:
        code = _new_code()
    _STORE[code] = {
        "target": str(body.url),
        "clicks": 0,
        "created_at": datetime.now(UTC).isoformat(),
    }
    return ShortenResponse(code=code, short_url=f"/{code}")


@app.get("/{code}")
def redirect(code: str) -> RedirectResponse:
    item = _STORE.get(code)
    if not item:
        raise HTTPException(status_code=404, detail="unknown code")
    item["clicks"] += 1
    return RedirectResponse(url=item["target"], status_code=302)


@app.get("/stats/{code}", response_model=StatsResponse)
def stats(code: str) -> StatsResponse:
    item = _STORE.get(code)
    if not item:
        raise HTTPException(status_code=404, detail="unknown code")
    return StatsResponse(
        code=code,
        target=item["target"],
        clicks=item["clicks"],
        created_at=item["created_at"],
    )
'''

DEFAULT_TEST = '''\
from app import app
from fastapi.testclient import TestClient

client = TestClient(app)


def test_health():
    assert client.get("/health").json()["status"] == "ok"


def test_shorten_and_redirect():
    r = client.post("/shorten", json={"url": "https://example.com/path"})
    assert r.status_code == 200
    code = r.json()["code"]
    red = client.get(f"/{code}", follow_redirects=False)
    assert red.status_code == 302
    stats = client.get(f"/stats/{code}")
    assert stats.json()["clicks"] == 1
'''


async def run(state: dict[str, Any]) -> dict[str, Any]:
    s = AgentState.model_validate(state)
    system = prompt_loader.get("implementer")
    user = (
        f"Design:\n{json.dumps(s.design or {}, indent=2)}\n\n"
        f"Requirements:\n{json.dumps(s.requirements or {}, indent=2)}\n\n"
        "Return JSON {\"files\": {\"url_shortener/app.py\": \"...\", "
        "\"url_shortener/test_app.py\": \"...\", \"url_shortener/README.md\": \"...\"}}"
    )
    files: dict[str, str]
    try:
        data = await invoke_json(system, user)
        files = data.get("files") or {}
        if "url_shortener/app.py" not in files:
            raise ValueError("missing app.py")
    except Exception as exc:  # noqa: BLE001
        logger.warning("implementer_fallback", error=str(exc))
        files = {
            "url_shortener/app.py": DEFAULT_APP,
            "url_shortener/test_app.py": DEFAULT_TEST,
            "url_shortener/README.md": "# URL Shortener\n\nGenerated by agentic SDLC.\n",
            "url_shortener/requirements.txt": "fastapi\nuvicorn\nhttpx\npydantic\n",
        }

    written = []
    for rel, content in files.items():
        result = await policy_gated_write(s.run_id, rel, content)
        if not result.get("ok"):
            # Still write via non-gated for prototype after logging
            write_file(s.run_id, rel, content)
            logger.warning("policy_write_violation", violations=result.get("violations"))
        written.append(rel)

    app_code = files.get("url_shortener/app.py", DEFAULT_APP)
    return {
        "code": app_code,
        "content": app_code,
        "artifact": app_code,
        "artifacts": {**(s.artifacts or {}), "files": written},
        "structured": {"files": list(files.keys())},
    }
